apiVersion: k3s.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: my-k3s-cluster
spec:
  forProvider:
    host: k3s-nodepool-0.k3s-nodepool.crossplane-system.svc.cluster.local
    port: 22
    k3sChannel: stable
    tlsSAN: k3s.example.com
    disableTraefik: true
  writeConnectionSecretToRef:
    name: k3s-cluster-kubeconfig
    namespace: crossplane-system
